snakegame.py
=> added a snake game

rock-paper-scissor-game.py
=> Added the rock paper scissor game

even-or-odd.py
=> Find whether the number is a even or odd

areacircle.py, rock-paper-scissor-game.py
=> find the area of circle

area.py
mekath accept kalla daam suddah
=> simple area finder

evensum.py, oddoreven.py
=> Odd or Even Number

guessing.py
=> Guessing Game

passwordgen.py
=> Password Generator

madlibs.py, tictac.py
=> Tic Tac Game

guessnumb.py
=> Number Guessing Game

binaryengine.py
=> Binary Search Engine

notifier.py
=> Desktop Notifier App

timer.py
=> Countdown Timer

sudoku.py
=> Sodoku Solver

manipulate.py
=> Photo Manipulation

cal.py, circle.py
=> Area of a circle

game.py
=> Super Enjoyable Snake Game

genpw.py
=> Password Generator Super Cool

odoreven.py
=> Odd or Even Finder

Socket/client.py, Socket/readme.md, Socket/server.py
A program representing client and server model to relay information using sockets. #41 
PS : Run the server.py first and then the client in two different terminals
=> Created a Chat Application

areacircle.py
Finding the area of the circle
=> Find out the area of the circle

even-or-odd-number.py, simple-cal.py
=> Added a simple calculator

pokémon_card_pricechecker.py
Give the program the Pokémon card data, and it'll give you present day average prices for the cards by scrapping data on ebay.
Helps solve #41
=> Created pokémon_card_pricechecker.py

rock-paper-scissor-game.py
=> Added a password Generator
